import Link from 'next/link'
import Head from 'next/head'
import Navbar from '/components/navbar'
import Game from '/components/tictactoeComponents/tic_tac_toe_game.js'
import styles from '/styles/tic_tac_toe.module.css'

export default function TicTacToe() {
    return (
        <>
            <Head>
                <title>Tic-Tac-Toe</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Navbar></Navbar>
            <h1 className="text-3xl font-bold underline text-center">
                Tic-Tac-Toe
            </h1>

            <div className={styles.gamespace}>
                <Game></Game>
            </div>
            <footer>
                <h3 className="absolute bottom-0 h-16 text-2xl hover:underline text-blue-600 dark:text-blue-400 font-bold">
                    <Link href="/">← Home</Link>
                </h3>
            </footer>
        </>
    )
}
