import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.module.css'
import Link from 'next/link'
import Navbar from '/components/navbar'
import Hero from "/components/hero";


export default function Home() {
    return (
        <>
            <Head>
                <title>
                    Ari Farber
                </title>
                <meta
                    name="description"
                    content="Nextly is a free landing page template built with next.js & Tailwind CSS"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <Hero />
        </>
    )
}

// <div>
//     <Navbar></Navbar>
//     <Head>
//         <title>Create Next App</title>
//         <meta
//             name="description"
//             content="Generated by create next app"
//         />
//         <link rel="icon" href="/favicon.ico" />
//     </Head>

//     <h1 className={styles.title}>Ari Farber</h1>
// </div>
